packages:
  # all packages in direct subdirs of packages/
  - "frontend"
  - "viter"
  # all packages in subdirs of components/
  - "components/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
